[org] Add org-cliplink package
syl20bnr/spacemacs pull request #12279
Opened 2019-05-09 11:00 UTC by bb2020

`org-cliplink` is amazing. Inserts link from kill ring into `org` buffer with the page's title.

2019-05-09 16:16 UTC, smile13241324 requested changes
Hi @bb2020,

I have just reviewed your PR, and would like to request some changes.
Please check my comments and mention me when you are ready for another review.

2019-05-09 16:16 UTC, smile13241324 commented on layers/+emacs/org/README.org
> +| ~SPC m i c~ | org-cliplink (insert link with page title) |
Please add the binding under `Element insertion` right under `SPC m i l`

2019-05-09 16:16 UTC, smile13241324 commented on layers/+emacs/org/packages.el
> +      "ic" 'org-cliplink)))
Please change the binding to `SPC m i L` instead.

2019-05-09 17:59 UTC, bb2020 commented
@smile13241324 Ready

2019-05-12 20:05 UTC, smile13241324 approved these changes

2019-05-12 20:18 UTC, smile13241324 commented
Thank you for contributing to Spacemacs!
The PR has been cherry-picked into the develop branch, you can safely delete your branch.

2019-05-12 20:18 UTC, closed without merging