Fix git-gutter+ refresh on Magit refresh
syl20bnr/spacemacs pull request #13958
Opened 2020-09-17 14:12 UTC by claritystorm

Fixed `git-gutter+` refresh when a buffer is staged or unstaged in Magit.

2020-09-18 18:15 UTC, smile13241324 approved these changes
Looks ok, will be merged soon

2020-09-18 18:28 UTC, smile13241324 commented
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.

2020-09-18 18:52 UTC, smile13241324 commented
I had to revert your PR, it has negative side effects when I stage a changed file and then commit. In this case I see the following error in the message buffer:
```
Error callling git diff:
```
Can you have another look?

2020-09-18 18:55 UTC, smile13241324 requested changes
Please see my previous commit for the side effects

2020-09-19 12:00 UTC, duianto commented
I've got an open issue about that error message here: 
`Error callling diff` message when syncing configuration layers: SPC f e R #11938

There's also an open issue about it on the `git-gutter-plus` repo, but it doesn't say much:
Getting 'Error callling diff" errors with latest magit · Issue https://github.com/nonsequitur/git-gutter-plus/issues/41

So that error might already have been there occurring in some specific situations, this PR just made it even more obvious.

2020-09-20 22:37 UTC, claritystorm commented
This error is reproduced by calling `git-gutter+-refresh` from a buffer visiting `.spacemacs`.

2020-09-23 19:40 UTC, smile13241324 approved these changes
Looks ok, when this is a known issue not coming from your change, I will merge it again.

2020-09-23 19:40 UTC, merged

2020-09-23 19:50 UTC, smile13241324 commented
Just retested now the issue is gone, thanks for committing again @claritystorm.

2021-05-11 07:47 UTC, MHOOO commented
For anyone who stumples accross performance issues when staging:
I have serious lag when staging changes in the magit status buffer (1-2s when pressing "s"). Removing `spacemacs//git-gutter+-refresh-in-all-buffers` from `magit-pre-refresh-hook` fixed that for me.

2021-05-16 19:38 UTC, smile13241324 commented
@MHOOO well looks like the issue is the number of buffers open in your emacs session. In the current implementation all of these are read which could take some seconds depending on the number of open buffers.

Maybe we should define an configurable max number of buffers to run through. Or change the implementation not to have to go through all open buffers for this.

I think this would justify an issue to discuss a possible solution.