Add instruction how to use ranger by default
syl20bnr/spacemacs pull request #13976
Opened 2020-09-23 19:27 UTC by dalanicolai

The ranger layer does not describe yet how to actually use ranger by default, while also the [instructions for the original ranger package](https://github.com/ralesi/ranger.el#setting-as-default-directory-handler) don't work (i.e. setting `ranger-override-dired` via customize does not work in Spacemacs).

I created a feature branch but forgot to check it out (still need to get used to magit). I hope it is fine that I create this PR now directly (and be more careful/wiser next time).

2020-09-23 20:27 UTC, smile13241324 requested changes
I like the addition to the documentation, however I have found a row which doesn't look like intended. Please double check and mention me when I should review again.

2020-09-23 20:27 UTC, smile13241324 commented on layers/+tools/ranger/README.org
> +To
This does not look right

2020-09-25 11:18 UTC, dalanicolai commented
@smile13241324 Sorry for that, I cleared it up now, so I guess it can be merged.

2020-09-27 12:34 UTC, smile13241324 approved these changes
Looks good now, will be merged soon.

2020-09-27 12:34 UTC, merged