[shell] new helm function to search history and bind it to M-r
syl20bnr/spacemacs pull request #14019
Opened 2020-10-05 21:35 UTC by thanhvg

Based on http://xenodium.com/search-bash-history-with-emacs-helm/

Add new helm function `spacemacs/helm-shell-search-history` to search
bash history and insert to vterm/shell

Bind this function to `M-r` for vterm and shell mode.

New layer variable `spacemacs-bash-history-file-locatition` to customize bash file

Other thoughts:
- probably should be opt-in
- need ivy implementation

Thank you for contributing to Spacemacs!

Before you submit this pull request, please ensure it is against the develop branch and not master.

This message should be replaced with a description of your change.

Thank you <3

2020-10-10 20:27 UTC, smile13241324 requested changes
Hi @thanhvg,

I have reviewed your PR and found some smaller issues you should fix before merging.
I have left more detailed information about the issues in the individual comments.

BR
MAx

2020-10-10 20:27 UTC, smile13241324 commented on layers/+tools/shell/config.el
> +(defvar spacemacs-bash-history-file-locatition "~/.bash_history"
Same here should be `spacemacs-bash-history-file-locatition`

2020-10-10 20:27 UTC, smile13241324 commented on layers/+tools/shell/README.org
> +=spacemacs-bash-history-file-locatition= can be customized to your bash hitory
Small typo, should be location. Hitory should be history.

2020-10-10 20:27 UTC, smile13241324 commented on layers/+tools/shell/packages.el
> +  (spacemacs//shell-bind-m-r shell-mode-map)
Whats the current default behaviour? If it is highly different to the helm/ivy based approach you should have a config var to activate it. The default would be nil by default meaning no new behaviour, t to activate completion support.

This is especially true as the default history file may be wrong for non bash shells like fish or zsh.

2020-10-27 23:27 UTC, thanhvg commented
Hi @smile13241324 thanks for the feed back. I just found out that we already have `, H` for history for `shell-mode`. So I will to remove `shell-mode` support from this PR, and keep the change for `vterm` only.

2020-10-30 20:16 UTC, smile13241324 approved these changes
Looks good now.

2020-10-30 20:17 UTC, merged

2020-10-30 20:17 UTC, smile13241324 commented
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.