[erlang] add LSP support through erlang_ls
syl20bnr/spacemacs pull request #14022
Opened 2020-10-07 22:39 UTC by cfclavijo

Basic changes to add LSP support for erlang layer using [erlang_ls](https://erlang-ls.github.io/) backend.
Supported [features](https://erlang-ls.github.io/features/) 
Example of my `dotspacemacs-configuration-layers`
```
(erlang :variables
             erlang-enable-lsp-mode t
             erlang-root-dir "/home/carlosrendon/.otp_builds/otp_22_kred/lib/erlang"
             erlang-man-root-dir "/home/carlosrendon/.otp_builds/otp_22_kred/lib/erlang/man"
             erlang-ls-path "/home/carlosrendon/.erlang_ls/_build/default/bin/"
             erlang-fill-column 100
             company-minimum-prefix-length 1
             lsp-ui-doc-position 'bottom
             projectile-enable-caching t)
```

Thank you <3

2020-10-15 21:40 UTC, smile13241324 requested changes
@cfclavijo I have just had a very brief look over your PR however I have noticed that it does not work like the other LSP related layers. Please have a look at `json` layer and try to change the layer to work in a similar fashion when it comes to setup lsp.

It is especially important to use a non bool backend variable. The variable must be initialised with `nil` which will result in choosing the backend after examining the loaded layers (includes lsp).

2020-10-15 21:40 UTC, smile13241324 commented on layers/+lang/erlang/layers.el
> +;; Copyright (c) 2020 Carlos F. Clavijo & Contributors
Please use the standard copyright notice

2020-10-16 20:33 UTC, cfclavijo commented
Hello, @smile13241324. I followed your comments, improved the way lsp backend is chosen, moved most of the config-related stuffs to func.el, updated docs and rebased

2020-10-22 22:03 UTC, smile13241324 requested changes
I have reviewed your PR and found some places you should change before this can be merged.
For details please check my comments.

2020-10-22 22:03 UTC, smile13241324 commented on layers/+lang/erlang/funcs.el
> +  (add-hook 'erlang-mode-hook 'company-mode))
This should not be directly called instead use `:append-hooks` tag of spacemacs|add-company-backends which will do the same.

2020-10-22 22:03 UTC, smile13241324 commented on layers/+lang/erlang/funcs.el
> +              :call-hooks t)
Are you sure you require call-hooks? Normally this is not necessary.

2020-10-26 22:29 UTC, smile13241324 approved these changes
Look good now :), I'll merge it in a minute.

2020-10-26 22:29 UTC, merged

2020-10-26 22:30 UTC, smile13241324 commented
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop. 
Welcome to the project :).