Specify configuration layers info pages and add cross links
syl20bnr/spacemacs pull request #14082
Opened 2020-10-22 11:09 UTC by dalanicolai

Searching for information about configuration layers is confusing because both
the overview and development info pages have the same title (try it with
google). Specifying those info pages title names and adding cross links makes
the docs friendlier.

NOTE!!! I have inserted relative links. But I'm afraid they will not work in the website, however I as I can not build the doc pages, I can not test the links. Maybe you could direct me to instructions about how to make 'internal' links (between different pages) in the Spacemacs docs.

2020-10-22 20:59 UTC, smile13241324 commented
I am not sure that this change will help, when you check the remarks in layers/layers.org you will notice that this file is auto generated so the text you have added will most likely be overwritten with the next bot run.

About the relative links maybe @JAremko can help you with this, I am not entirely sure how this file is build and what to do to change its headline. However I would expect that the change would rather need to be made in the template than in the generated file.

2020-10-23 11:31 UTC, JAremko commented
Changes to `doc/LAYERS.org` should work. And @smile13241324  right  `layers/LAYERS.org` will get overridden. We can set title for  `layers/LAYERS.org` to something like "layers list" to make it even less confusing.

You can change the title by adding `:spacetools.spacedoc.config/layers-org-title-text "new title"` and the text by `:spacetools.spacedoc.config/layers-org-description "new text"` into
 https://github.com/syl20bnr/spacemacs/blob/develop/.ci/spacedoc-cfg.edn#L83

current value for description text is
```
"This file is auto-generated!\nDon't edit it directly.\nSee [[https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org#readmeorg-tags][\"README.org tags\" section of CONTRIBUTING.org for the instructions]].
```

2020-10-23 11:36 UTC, JAremko commented
also you can test it locally with docker

``` sh
docker run --rm  -v <spacemacs_root_dir>:/tmp/docs/ 
                 -v <config_file>:/opt/spacetools/spacedoc-cfg.edn 
                 jare/spacetools docfmt /tmp/docs/`
```

it will reformat all docs and generate new layers.org.

2020-10-23 16:14 UTC, smile13241324 requested changes
@dalanicolai please check JAremko's comment and do the changes for the generated layers.org file at the specified location, also please check the generation locally.

2020-10-25 16:39 UTC, dalanicolai commented
I was trying to reformat the docs but while many README's are exported successfully still, despite that I synced with latest develop branch, the process stops with the following error:

!!!!!!!!!!!!!!!! ERROR !!!!!!!!!!!!!!!!
current-buffer: INSTALL.org<2>
current-file: /tmp/docs/layers/+emacs/org/local/gnuplot/INSTALL.org
error: Link "Installing without configure or make" has unknown type "fuzzy"
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
Unfortunately I do not know what that means. Any suggestion?

2020-10-25 16:57 UTC, JAremko commented
@dalanicolai  you're probably using old Spacemacs revision.  I don't see file `gnuplot` dir here https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bemacs/org/local

try running  bot over up to date develop fork.

2020-10-26 09:20 UTC, JAremko commented
also you can temporary delete INSTALL.org

2020-10-28 00:38 UTC, dalanicolai commented
Thanks for the nice instructions. So I totally forgot that I had manually installed gnuplot and did not notice it was in the local directory and I did not understand the docker command completely.

Anyway, I fixed the PR now and tested the result. I thought "Spacemacs layers list" to be a nice title, as this corresponds more or less were I would google for intuitively. But of course, otherwise better suggestions are welcome also.

2020-10-28 19:26 UTC, JAremko commented
Good job :+1:

2020-10-30 20:03 UTC, smile13241324 approved these changes
Looks good

2020-10-30 20:11 UTC, smile13241324 commented
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.

2020-10-30 20:11 UTC, closed without merging