Add grip-mode to github layer
syl20bnr/spacemacs pull request #14120
Opened 2020-11-08 11:18 UTC by dalanicolai

Grip-mode renders a preview of github README files locally, so you can check how they look before pushing to github.
I figured that more people would like it, and that it would be great to have this as standard functionality in the github layer.
I've added it under keybindings `SPC g h p` for start grip mode and `SPC g h P` for stop grip-mode.

2020-11-12 21:31 UTC, smile13241324 requested changes
Can you explain a bit more about the preference of =grip-mode= vs =vmd-mode=? We can have both but right now they look pretty identical. However both should be located in the `markdown` layer and be bound to a mode specific binding for previewing in addition to a org mode binding possibly under `SPC m T m` similar to what we have with previewing Latex.

2020-11-13 15:13 UTC, dalanicolai commented
First I did not know about vmd-mode. But now that I have looked at it, I have noticed a few things:
1. vmd-mode only supports markdown preview, although probably quite straightforward, a function to preview org-mode files has not been included yet.
2. vmd-mode is installed using `npm` while grip is installed using `pip`. In this respect I think maybe both should be supported, so that users can use the package they prefer (personally I am not very familiar with npm, while pip I know quite well)

A third point is that, although `grip-mode` renders markdown or org files, for me it is more logical that this functionality belongs to "github tools/layer" and not really to "markdown/org tools/layers". There is no real no need to have the markdown layer or org layer installed for writing github README's, a user could just use `grip-mode` directly. On the other hand, I somewhat agree with you too, but if it is only added to markdown/org layers then I think that at least the github preview functionality should be mentioned/referred to from the github layer.

Overall, I think users are welcome to add vmd-mode functionality to the org layer and refer to it from the github layer. But I think the proposal in this PR is a quite small and welcome addition (only a small file and a single keybinding). Also I find it quite intuitive to add it under the `SPC g h`, but I agree that markdown/org major-mode keybindings would be nice too. Although in that case it might be more intuitive to create a prefix `preview` under `SPC m p` and also move the latex preview there...

2020-11-14 08:46 UTC, smile13241324 approved these changes
I think you are right, the current proposal is straight forward and will be helpful for most people for now. We still should try not to duplicate functionality but we can revise this later.

2020-11-14 08:46 UTC, smile13241324 commented on layers/+source-control/github/README.org
> +system. Grip can usually be installed with the command =pip3 install grip=.
This should definitely refer to "pip" not "pip3". "pip3" is only available on debian based systems.

2020-11-14 08:47 UTC, smile13241324 commented on layers/+source-control/github/README.org
> +system. Grip can usually be installed with the command =pip3 install grip=.
Never mind I will change it myself

2020-11-14 08:47 UTC, merged