Revert helm-ag binding of RET to default
syl20bnr/spacemacs pull request #14158
Opened 2020-11-23 00:05 UTC by kini

Currently 'helm-ag-mode-jump-other-window is bound both to RET and to C-o (its
original default binding), while 'helm-ag-mode-jump isn't bound at all (its
original default binding is RET).  This commit removes our customization so that
both 'helm-ag-mode-jump-other-window and 'helm-ag-mode-jump have bindings in the
mode.

2020-11-24 21:01 UTC, smile13241324 requested changes
I don't agree with your change, when you have a look at helm/packages.el you will notice that for all helm based functions the `*-other-window` version is called with `RET`. Also `C-o` is definitely unbound for `Evil` users.

Do you have a specific use-case where the current binding pose a problem?

2020-11-24 21:51 UTC, kini commented
> I don't agree with your change, when you have a look at helm/packages.el you will notice that for all helm based functions the `*-other-window` version is called with `RET`. Also `C-o` is definitely unbound for `Evil` users.
> 
> Do you have a specific use-case where the current binding pose a problem?

Hmm. `C-o` is not unbound for me and I am an Evil user. This is for the keymap that's used in the `*helm ag results*` buffer that appears when you do (e.g.) `SPC /`, search for something, and hit `<f3>`. I don't think I've configured anything differently that would affect this. Can you check again whether `C-o` is unbound for Evil users?

As for the other helm based functions, I only see one other `RET` binding to a `*-other-window` function, which is the binding of `helm-grep-mode-jump-other-window`, i.e. the analogue of `helm-ag-mode-jump-other-window` when using `grep` instead of `ag`. The `helm-grep` upstream package has analogous bindings to the `helm-ag` upstream package (see [here](https://github.com/emacs-helm/helm/blob/5ad6c83681fda7bfd5a745fedecaa924630253dd/helm-grep.el#L346-L347)) so I suppose it's more consistent to change that binding as well. I'll add that change to my commit, too.

The specific use case is that I hit `<f3>` during a search, and then when I have the search results buffer open, there's no key binding for `'helm-ag-mode-jump`. I could just add a key binding in my `.spacemacs`, sure, but since the upstream package provides a binding for that function already and Spacemacs deletes it for no apparent reason, I figured it's better to change Spacemacs in this case.

2020-11-25 08:25 UTC, smile13241324 commented
Thanks for the explanation I will check

2020-11-27 18:19 UTC, smile13241324 approved these changes
Now I see your point, in this case you are right, the default for Return should be `jump-window`, the default binding `C-o` for `jump-other-window` should be enough for most people.

2020-11-27 18:19 UTC, merged

2020-11-27 18:19 UTC, smile13241324 commented
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.