Validate layer variables if they are defcustoms
syl20bnr/spacemacs pull request #14372
Opened 2021-02-11 17:51 UTC by JAremko

@smile13241324 ,  @duianto and  @sdwolfz  discussed if it makes sense to use defcustom for layer variables to solve issues like #14343 

This is a demo.

To test the validation You can try replacing something like:

``` elips
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom)
``` 
in  Your .spacemacs file with a bad value:

``` elisp
     (shell :variables
            shell-default-height "foobar"
            shell-default-position 'bottom)
```

2021-02-13 08:39 UTC, smile13241324 commented
I'll give it a try this evening

2021-02-14 08:33 UTC, smile13241324 reviewed
I have played a bit around with this new function and I think I have found one or two smaller issues.

I also had to fix a loading order issue in `init-window-purpose` which seems to be triggered by the
changes here. No idea why, but actually emacs was right and the init function was implicitly relying on
magit being loaded already. See af0d0e72763c6b441087dfdb96b65020c3c43650.

I think the next step would be to test how these config vars play with the native emacs config UI i.e.
do we loose settings when some are set via the dotfile and some are set via this user-config function.
But I need some time to read into this topic first :).

2021-02-14 09:27 UTC, JAremko commented on core/core-configuration-layer.el
> +                       (validate-variable var))
@smile13241324  try ` #'godoc-at-point-function 'godoc-gogetdoc`

2021-02-14 09:35 UTC, JAremko commented
> I think we should only validate custom vars right now, see the function invariant below:

@smile13241324  Yeah also we can start by validating only Spacemacs defined defcustoms. I'm not quite sure how it affects auto loads :thinking:

2021-02-14 13:28 UTC, smile13241324 commented on core/core-configuration-layer.el
> +                       (validate-variable var))
Woah you are right, declaring the function properly with `#'` seems to do the trick.

2021-02-14 13:30 UTC, smile13241324 commented
@JAremko jup I think this would be best lets focus on our variables at least in the beginning. We can still allow people to optionally activate the checks for all their custom vars as a kind of curated user-config feature in the dotfile.

2021-02-15 19:46 UTC, JAremko commented
@smile13241324  ok so now root menu of customization UI has "Spacemacs" entry with sub entry "Spacemacs layers" that will have all your enabled layer listed.  The validation code will only run if the config var defined via our new macro `spacemacs|defc`

2021-02-15 20:01 UTC, JAremko commented
We can find most of config variables with `find . -type f -name config.el -print | xargs grep -n "(defvar "` (from .emacs.d)

This is what I currently get:

```
./layers/+music/pianobar/config.el:12:(defvar pianobar-config 'nil
./layers/+music/pianobar/config.el:16:(defvar pianobar-command "pianobar"
./layers/+music/pianobar/config.el:20:(defvar pianobar-station 'nil
./layers/+spacemacs/spacemacs-evil/config.el:13:(defvar vim-style-visual-feedback nil
./layers/+spacemacs/spacemacs-evil/config.el:16:(defvar hybrid-style-visual-feedback nil
./layers/+spacemacs/spacemacs-evil/config.el:19:(defvar evil-lisp-safe-structural-editing-modes '()
./layers/+spacemacs/spacemacs-evil/config.el:22:(defvar spacemacs-evil-collection-allowed-list '(eww dired)
./layers/+spacemacs/spacemacs-completion/config.el:15:(defvar helm-use-fuzzy (spacemacs|dotspacemacs-backward-compatibility
./layers/+spacemacs/spacemacs-completion/config.el:21:(defvar helm-enable-auto-resize (spacemacs|dotspacemacs-backward-compatibility
./layers/+spacemacs/spacemacs-completion/config.el:33:  (defvar helm-source-header-default-background
./layers/+spacemacs/spacemacs-completion/config.el:35:  (defvar helm-source-header-default-foreground
./layers/+spacemacs/spacemacs-completion/config.el:37:  (defvar helm-source-header-default-box
./layers/+spacemacs/spacemacs-completion/config.el:39:  (defvar helm-source-header-default-height
./layers/+spacemacs/spacemacs-layouts/config.el:14:(defvar spacemacs-layouts-directory
./layers/+spacemacs/spacemacs-layouts/config.el:18:(defvar layouts-enable-autosave nil
./layers/+spacemacs/spacemacs-layouts/config.el:21:(defvar layouts-autosave-delay 900
./layers/+spacemacs/spacemacs-layouts/config.el:24:(defvar spacemacs--layouts-ts-full-hint-toggle nil
./layers/+spacemacs/spacemacs-layouts/config.el:27:(defvar spacemacs--workspaces-ts-full-hint-toggle nil
./layers/+spacemacs/spacemacs-layouts/config.el:30:(defvar spacemacs--last-selected-layout dotspacemacs-default-layout-name
./layers/+spacemacs/spacemacs-layouts/config.el:33:(defvar spacemacs--custom-layout-alist nil
./layers/+spacemacs/spacemacs-layouts/config.el:37:(defvar spacemacs--layouts-autosave-timer nil
./layers/+spacemacs/spacemacs-layouts/config.el:40:(defvar spacemacs-generic-layout-names
./layers/+spacemacs/spacemacs-layouts/config.el:61:(defvar spacemacs-layouts-restricted-functions
./layers/+spacemacs/spacemacs-layouts/config.el:67:(defvar spacemacs-layouts-restrict-spc-tab nil
./layers/+spacemacs/spacemacs-layouts/config.el:70:(defvar layouts-enable-local-variables t
./layers/+spacemacs/spacemacs-layouts/config.el:73:(defvar spacemacs--layout-local-variables nil
./layers/+spacemacs/spacemacs-layouts/config.el:76:(defvar spacemacs--layout-local-map (spacemacs-ht-create)
./layers/+spacemacs/spacemacs-defaults/config.el:28:(defvar spacemacs-useless-buffers-regexp '()
./layers/+spacemacs/spacemacs-defaults/config.el:30:(defvar spacemacs-useful-buffers-regexp '()
./layers/+chat/slack/config.el:14:(defvar slack-spacemacs-layout-name "@Slack"
./layers/+chat/slack/config.el:17:(defvar slack-spacemacs-layout-binding "s"
./layers/+chat/erc/config.el:12:(defvar erc-enable-sasl-auth nil
./layers/+chat/erc/config.el:15:(defvar erc-spacemacs-layout-name "@ERC"
./layers/+chat/erc/config.el:18:(defvar erc-spacemacs-layout-binding "E"
./layers/+chat/erc/config.el:21:(defvar erc-server-list nil
./layers/+chat/erc/config.el:24:(defvar erc-enable-notifications t
./layers/+chat/rcirc/config.el:14:(defvar rcirc-enable-authinfo-support nil
./layers/+chat/rcirc/config.el:17:(defvar rcirc-enable-emojify nil
./layers/+chat/rcirc/config.el:20:(defvar rcirc-enable-erc-image nil
./layers/+chat/rcirc/config.el:23:(defvar rcirc-enable-erc-tweet nil
./layers/+chat/rcirc/config.el:26:(defvar rcirc-enable-erc-yt nil
./layers/+chat/rcirc/config.el:29:(defvar rcirc-enable-late-fix nil
./layers/+chat/rcirc/config.el:32:(defvar rcirc-enable-styles nil
./layers/+chat/rcirc/config.el:35:(defvar rcirc-enable-znc-support nil
./layers/+chat/rcirc/config.el:38:(defvar rcirc-spacemacs-layout-name "@RCIRC"
./layers/+chat/rcirc/config.el:41:(defvar rcirc-spacemacs-layout-binding "i"
./layers/+readers/elfeed/config.el:14:(defvar elfeed-enable-web-interface nil
./layers/+readers/elfeed/config.el:16:(defvar elfeed-enable-goodies t
./layers/+readers/deft/config.el:14:(defvar deft-zetteldeft nil
./layers/+readers/dash/config.el:12:(defvar dash-autoload-common-docsets t
./layers/+readers/dash/config.el:15:(defvar dash-docs-docset-newpath "~/.docsets"
./layers/+fun/games/config.el:14:(defvar spacemacs-games-cache-directory
./layers/+source-control/git/config.el:14:(defvar git-enable-magit-svn-plugin nil
./layers/+source-control/git/config.el:17:(defvar git-magit-status-fullscreen nil
./layers/+source-control/git/config.el:20:(defvar git-enable-magit-delta-plugin nil
./layers/+source-control/git/config.el:23:(defvar spacemacs--git-blame-ts-full-hint-toggle nil
./layers/+source-control/version-control/config.el:12:(defvar spacemacs--smerge-ts-full-hint-toggle nil
./layers/+source-control/version-control/config.el:15:(defvar version-control-global-margin t
./layers/+source-control/version-control/config.el:18:(defvar version-control-diff-tool 'git-gutter+
./layers/+source-control/version-control/config.el:22:(defvar version-control-diff-side 'right
./layers/+misc/multiple-cursors/config.el:14:(defvar multiple-cursors-backend 'evil-mc
./layers/+misc/ietf/config.el:12:(defvar ietf-docs-cache (concat spacemacs-cache-directory "ietf-docs-cache")
./layers/+distributions/spacemacs-bootstrap/config.el:13:(defvar spacemacs--indent-variable-alist
./layers/+distributions/spacemacs-bootstrap/config.el:49:(defvar vim-style-remap-Y-to-y$
./layers/+distributions/spacemacs-bootstrap/config.el:54:(defvar vim-style-retain-visual-state-on-shift
./layers/+distributions/spacemacs-bootstrap/config.el:60:(defvar vim-style-visual-line-move-text
./layers/+distributions/spacemacs-bootstrap/config.el:65:(defvar vim-style-ex-substitute-global
./layers/+distributions/spacemacs-bootstrap/config.el:71:(defvar spacemacs-evil-cursors '(("normal" "DarkGoldenrod2" box)
./layers/+completion/helm/config.el:22:(defvar helm-no-header (spacemacs|dotspacemacs-backward-compatibility
./layers/+completion/helm/config.el:26:(defvar helm-position (spacemacs|dotspacemacs-backward-compatibility
./layers/+completion/helm/config.el:30:(defvar spacemacs-helm-rg-max-column-number 512
./layers/+completion/helm/config.el:37:(defvar spacemacs-helm-display-help-buffer-regexp '("*.*Helm.*Help.**"))
./layers/+completion/helm/config.el:38:(defvar spacemacs-helm-display-buffer-regexp
./layers/+completion/helm/config.el:45:(defvar spacemacs-display-buffer-alist nil)
./layers/+completion/auto-completion/config.el:14:(defvar spacemacs-default-company-backends
./layers/+completion/auto-completion/config.el:25:(defvar auto-completion-return-key-behavior 'complete
./layers/+completion/auto-completion/config.el:29:(defvar auto-completion-tab-key-behavior 'cycle
./layers/+completion/auto-completion/config.el:33:(defvar auto-completion-complete-with-key-sequence nil
./layers/+completion/auto-completion/config.el:37:(defvar auto-completion-complete-with-key-sequence-delay 0.1
./layers/+completion/auto-completion/config.el:41:(defvar auto-completion-minimum-prefix-length 2
./layers/+completion/auto-completion/config.el:44:(defvar auto-completion-idle-delay 0.2
./layers/+completion/auto-completion/config.el:47:(defvar auto-completion-enable-snippets-in-popup nil
./layers/+completion/auto-completion/config.el:50:(defvar auto-completion-enable-sort-by-usage nil
./layers/+completion/auto-completion/config.el:53:(defvar auto-completion-enable-help-tooltip nil
./layers/+completion/auto-completion/config.el:58:(defvar auto-completion-use-company-box nil
./layers/+completion/auto-completion/config.el:61:(defvar company-mode-completion-cancel-keywords
./layers/+completion/auto-completion/config.el:69:(defvar auto-completion-pri [...]

2021-02-15 20:04 UTC, JAremko commented
When we done with implementing this we'll need a breave soul to update docs and curate crowd-coded update for the configs.

I think the examples I provided (in this PR) + a case with function (to point out that it should be `#'foobar` not just `'foobar`) should be sufficient :thinking:

2021-02-16 14:17 UTC, JAremko commented
I'll write the docs myself + expand this to also validate .spacemacs variables.

2021-02-16 14:19 UTC, JAremko commented on core/core-configuration-layer.el
> +     :group ,(or group-override (quote spacemacs--current-customization-group)))))
should default to 'spacemacs group.  Also should dry to infer the group based on buffer's file  (in case of buffer evaluation)

2021-02-16 20:42 UTC, smile13241324 requested changes
The handling within Spacemacs seems to be working very stable already. I have set some specific settings via `custom-set-variables` and this was also working very good.

Then I had a closer look at `customise`, there it looks like we still have some issues:
- Looks like there are some of the default dotfile variables already in there but always shown as "changed" when I try to save them it seems to have no effect. I had this behaviour for `spacemacs-yank-indent-modes`. Not sure if this comes from this change or was always the case though :thinking:. 
- I have noticed that the config groups for all available layers are created independent of whether I have them loaded or not. This makes finding the interesting variables for my config difficult. Is it possible to only define the group and vars if the layer is also loaded?

2021-02-18 02:23 UTC, JAremko commented
Ok so now layer customization are split by categories. The rest of the junk under Spacemacs category will need some categories too. But for now I'll see how to incorporate vars of .spacemacs into all of this :thinking:

2021-02-21 21:27 UTC, smile13241324 requested changes
I still see the issue that the custom groups of all layers are defined independent of whether the layer is loaded or not. These groups should not be available until the layer is loaded.

![image](https://user-images.githubusercontent.com/18098560/108639264-ee2eef80-7493-11eb-8bc0-9c01ada0c9b1.png)

2021-02-21 21:33 UTC, JAremko commented
@smile13241324  this is strange since I only see used layers.  It's quite a lot, like 5 of them are coming from spacemacs distro.

2021-02-21 21:34 UTC, smile13241324 commented
Strange, let me double check maybe I don't have the latest version

2021-02-21 21:35 UTC, JAremko commented
@smile13241324  also maybe nuke saved custom vars in .spacemacs.  Just to be sure :thinking:

2021-02-21 21:44 UTC, smile13241324 commented
My mistake, my branch was not up-to-date now its working fine. Looks very neat now :+1:

2021-02-21 21:44 UTC, smile13241324 approved these changes

2021-02-21 21:46 UTC, JAremko commented
@smile13241324  we still have to put those "rogue" vars from spacemacs group somewhere.

2021-02-21 21:56 UTC, smile13241324 commented
@JAremko Maybe we could make a dotfile group and move it there? I think that's the primary source of these.

2021-03-18 13:21 UTC, JAremko commented
Apologies in advance to all the people with "not strictly valid" dotfiles :roll_eyes:

2021-03-18 13:43 UTC, JAremko commented
@smile13241324  I decided to make only layer level configs customizable with Emacs thingy since the vars have low discoverability  + there are many other package related vars that can be customized via native Emacs interface.  .spacemacs vars
should have a singe source of trust to make .spacemacs shareable and they are all listed in the file.  Down the line I'll make all the configs customizable via org-mode tool that will update .spacemacs file. This way we'll get best of both worlds - type guided customization with instant value validation  while all the stuff will be stored in a single place.

2021-03-18 13:47 UTC, merged