[haskell] Add a binding to change the target for the session
syl20bnr/spacemacs pull request #14451
Opened 2021-03-03 08:36 UTC by magthe

Using the correct target for the Haskell session is required when working on a
project with more than one target defined in the Cabal file.

2021-03-03 14:29 UTC, Kazark approved these changes

2021-03-13 23:18 UTC, smile13241324 requested changes
This is a sensible addition to the layer however this must also be documented in the org file of the layer.

2021-03-13 23:18 UTC, smile13241324 commented on layers/+lang/haskell/packages.el
> +          "st"  'haskell-session-change-target
New bindings must be documented in the layer readme.

2021-03-14 08:48 UTC, smile13241324 approved these changes
Now it looks good, will be merged in a minute.

2021-03-14 08:48 UTC, merged