Update to default behaviour
syl20bnr/spacemacs pull request #14470
Opened 2021-03-10 23:34 UTC by EstebanMarin

When working long hours with Metals and saving and moving between buffers. This feature of automatically showing and writing in buffers breaks HELM, and buffer management stops, rendering Emacs useless. Furthermore, this feature is not that useful. In VIM LSP is off by default. The purpose of this is to make the experience of Scala Developers with Metals a nice one, rather than having Emacs breaking all the time, as has been happening to me. This has saved me hours.

Thank you :heart: for contributing to Spacemacs!

Before you submit this pull request, please ensure it is against the `develop` branch and that you have read the [CONTRIBUTING.org](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org) file. It contains instructions on how to properly follow our conventions on commit messages, documentation, change log entries and other elements.

Don't forget to update CHANGELOG.develop if you want to be mentioned in the release file!

This message should be replaced with a description of your change.

Cheers!

2021-03-11 14:56 UTC, Kazark approved these changes
I absolutely agree that this is a better default. While some make like this UI, and that's fine, it is rather intrusive; it feels more like VSCode than Emacs; and as noted, even if this treeview works well with other LSP projects, it does not seem to play well with Metals in particular. 👍

2021-03-13 22:22 UTC, smile13241324 requested changes
I agree, if this function is not working reliably and even makes emacs freeze, it should be disabled by default.

This default change however must be documented in the readme, i.e. the current instructions to disable that feature must be changed to enabling it and a short warning should be added that this could cause performance issues.

2021-03-17 00:21 UTC, EstebanMarin commented
@smile13241324 I added the description in the `README.md` file. Please let me know if you want more changes.

2021-03-20 21:02 UTC, smile13241324 commented
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.

2021-03-20 21:02 UTC, closed without merging