[defaults] add qickrun
syl20bnr/spacemacs pull request #14622
Opened 2021-04-12 05:00 UTC by thanhvg

bind it to `SPC x x`, not sure it's the right place but it's easy to invoke.

2021-04-12 07:38 UTC, lebensterben commented
What's the use case?
The functionality seems to be covered already.

2021-04-15 20:31 UTC, smile13241324 requested changes
Looks ok, just found a small typo in the docs, the rest is ok.

I am not sure whether `SPC x x` is the right place, one could read it as `text -> execute`.
However something like eval would be better, however I don't see a better matching place in the global key map right now, maybe compile? Not sure, lets keep it in `SPC x x` and see how it works out.

2021-04-15 20:31 UTC, smile13241324 commented on doc/DOCUMENTATION.org
> +Spacemacs can excute current buffer or region.
```suggestion
Spacemacs can execute current buffer or region.
```

2021-04-19 20:10 UTC, smile13241324 approved these changes
:+1:

2021-04-19 20:20 UTC, smile13241324 commented
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.

2021-04-19 20:20 UTC, closed without merging