[visual][popwin] add keybiding to resume last popwin buffer
syl20bnr/spacemacs pull request #14623
Opened 2021-04-12 05:09 UTC by thanhvg

bind it to `spc r w`

2021-04-12 13:02 UTC, Kazark commented
I noticed that some Helm searches can be resumed with `SPC s l` but not always. Is this related at all? I would really love to be able to resume all Helm searches.

2021-04-12 14:41 UTC, thanhvg commented
No this just resumes popwin buffer such as *help* buffer,  lsp document at point buffer etc. 

Re helm I don't know, helm seems to prevents some commands from resuming I switched to ivy and it seems that ivy can resume almost anything. Btw I also bind `spc r L` to `C-u spc r l` not sure if it's worth a PR but it is extremely useful.

2021-04-15 20:20 UTC, smile13241324 requested changes
Nice change, only missing thing is the GPLv3 header we have been asked to add, otherwise we will get into trouble with the FSF.

2021-04-15 20:20 UTC, smile13241324 commented on layers/+spacemacs/spacemacs-visual/config.el
> +;;; License: GPLv3
This line must be replaced with the proper GPLv3 header

2021-04-15 20:21 UTC, smile13241324 commented
Yeah helm is a buggy beast, still I largly prefer it to ivy which I find so much lacking in comparison.

2021-04-16 13:23 UTC, Kazark commented
@smile13241324 off the top of my head, certainly I can't resume `SPC s s`. I'll post the other ones here as a re-encounter them.

2021-04-19 20:15 UTC, smile13241324 approved these changes
:+1:

2021-04-19 20:19 UTC, smile13241324 commented
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.

2021-04-19 20:19 UTC, closed without merging

2021-05-24 11:31 UTC, smile13241324 commented
Interesting, never noticed that there is a difference between the two. Thanks for the hint I will double check