[new layer] nav-flash
syl20bnr/spacemacs pull request #14625
Opened 2021-04-12 05:31 UTC by thanhvg

Ported from Doom

2021-04-12 23:28 UTC, lebensterben requested changes

2021-04-12 23:28 UTC, lebensterben commented on layers/+misc/nav-flash/config.el
> +(defvar nav-flash-exclude-commands
Need to add header
https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org#file-header

2021-04-12 23:28 UTC, lebensterben commented on layers/+misc/nav-flash/funcs.el
> +;;; funcs -*- lexical-binding: t; -*-
Need to add header
https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org#file-header

2021-04-12 23:28 UTC, lebensterben commented on layers/+misc/nav-flash/packages.el
> +;;; packages.el --- nav-flash layer packages file for Spacemacs.
Need to update header
https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org#file-header

2021-04-15 20:00 UTC, smile13241324 requested changes
New functionality is ok, still you should adress the points lebensterben pointed out above.

2021-04-15 20:00 UTC, smile13241324 commented on layers/+misc/nav-flash/packages.el
> +;;; packages.el ends here
No packages.el ends here line please

2021-04-15 20:00 UTC, smile13241324 commented on layers/+misc/nav-flash/packages.el
> +;;; Code:
Please remove these two comments

2021-04-19 20:25 UTC, smile13241324 approved these changes
Looks good now

2021-04-19 20:25 UTC, merged

2022-07-26 04:58 UTC, lebensterben commented
This PR has a major issue.

It's ported from Doom Emacs, which has MIT license.
But the files added in this PR wrongly used GPL-v3 license.

I'm working on a fix now.

2022-07-26 06:06 UTC, thanhvg commented
@lebensterben  you seem to have a lot of free time on this frivolous matter that imo is truly harmful to the community. Google told me MIT is compatible with GPL so I don't see any problem here. 

But I'm asking you @syl20bnr @smile13241324 and @JAremko those who I am assumed to be the owners of this project to be clear on this matter. Are my contributions breaking any rule? Do you allow code from SO, reddit, blogs or other elisp projects. If you don't  then please consider removing all of my changes because most of them I got inspired by the sources mentioned above or they were plain copy pasta.

Thanks.

2022-07-26 06:21 UTC, lebensterben commented
@thanhvg 

GPL 3.0 is compatible with MIT license. But you must include the copyright notice of MIT even after you re-licensed the work.

MIT license requires:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

A relative issue is that you didn't mention the copyright of Henrik Lissner.

Even though there are additional changes made upon his original work, his copyright persists.

I've already fixed this issue in a this commit c2903ad64a6317d0b88a3ce721bebe5aa1c14896.

---

>  Are my contributions breaking any rule? Do you allow code from SO, reddit, blogs or other elisp projects. If you don't then please consider removing all of my changes because most of them I got inspired by the sources mentioned above or they were plain copy pasta.

https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org#license reads:

> For files not belonging to Spacemacs like local packages and libraries, refer to the header file. Those files should not have an empty header, we may not accept code without a proper header file.

You must make contributions with due diligence. If your PR contains or is based on on other people's non-trivial work, you must respect the copyright of the original author, as well as the original license, if there is.

2022-07-26 07:18 UTC, JAremko commented
@thanhvg   

The owner is  @syl20bnr you can try contacting him via email. I don't think he has GitHub mention notifications on.