Warn about pdumper not working together with Native Compilation
syl20bnr/spacemacs pull request #14730
Opened 2021-05-02 13:42 UTC by sdwolfz

Pdumper does not work with Native Compilation. Reference: https://lists.gnu.org/r/bug-gnu-emacs/2020-12/msg00589.html

Updated docs and config with a warning.

2021-05-02 14:16 UTC, lebensterben requested changes

2021-05-02 14:16 UTC, lebensterben commented on core/templates/.spacemacs.template
> +   ;; If non-nil then enable support for the portable dumper. You'll need to
need to check the line length

2021-05-02 14:16 UTC, lebensterben commented on core/templates/.spacemacs.template
> +   ;; WARNING: pdumper does not work with Native Compilation, so if you get an
this is too intrusive. I prefer to keep this shorter.

Also, the better way of handling this is to disable pdump automatically when native compilation is enabled.

2021-05-06 02:31 UTC, syl20bnr commented
Is it possible to detect that Native Compilation is enabled ?
If yes, I agree that we should find a way to disable it automatically and print a message in the message buffer about it.

2021-05-06 03:13 UTC, lebensterben commented
@syl20bnr 

If `comp-ensure-native-compiler` doesn't throw error and if `comp-speed` is not -1,
then native-compilation is available and enabled.

```elisp
(defcustom comp-speed 2
  "Optimization level for native compilation, a number between -1 and 3.
 -1 functions are kept in bytecode form and no native compilation is performed.
  0 native compilation is performed with no optimizations.
  1 light optimizations.
  2 max optimization level fully adherent to the language semantic.
  3 max optimization level, to be used only when necessary.
    Warning: with 3, the compiler is free to perform dangerous optimizations."
  :type 'integer
  :safe #'integerp
  :version "28.1")
```

```elisp
 (defun comp-ensure-native-compiler ()
   "Make sure Emacs has native compiler support and libgccjit can be loaded.
 Signal an error otherwise.
 To be used by all entry points."
   (cond
    ((null (featurep 'native-compile))
     (error "Emacs was not compiled with native compiler support (--with-native-compilation)"))
    ((null (native-comp-available-p))
     (error "Cannot find libgccjit library"))))
```

2021-09-26 15:43 UTC, sdwolfz commented
Let's deal with this when emacs 28 will be released.

2022-02-03 05:23 UTC, lebensterben commented
I've just updated it so that pdumper is not enabled when native compilation is enabled.

2022-02-03 05:24 UTC, lebensterben approved these changes

2022-02-03 09:26 UTC, sdwolfz commented
Thanks for picking up the work and ressurecting this @lebensterben

2022-02-03 19:35 UTC, lebensterben commented
merging now.

2022-02-03 19:36 UTC, merged