Two wrong brackets in new EXWM layer
syl20bnr/spacemacs pull request #14802
Opened 2021-05-27 11:35 UTC by moritzschaefer

The PR for SpacemacsOS/EXWM leads to two errors for me (see last comment in https://github.com/syl20bnr/spacemacs/pull/14714)

2021-05-27 12:05 UTC, lebensterben commented
I will fix this later today

2021-05-28 01:29 UTC, lebensterben requested changes

2021-05-28 01:29 UTC, lebensterben commented on layers/+window-management/exwm/funcs.el
> -           (collect (xdg-desktop-read-file file))))
Change the function body to
```elisp
(cl-loop with autostart-dirs    =  nil
         with autostart-entries =  nil
         for  xdg-dir           in (cons (xdg-config-home) (xdg-config-dirs))
         for  autostart-dir     =  (expand-file-name (concat xdg-dir "/autostart"))
         when (and (file-exists-p autostart-dir)
                   (not (member autostart-dir autostart-dirs)))
           collect autostart-dir into autostart-dirs
           and nconc (mapcar #'xdg-desktop-read-file
                             (directory-files autostart-dir t ".+\\.desktop$")) into autostart-entries
         finally do (print autostart-entries))
```

2021-05-28 01:56 UTC, lebensterben commented on layers/+window-management/exwm/funcs.el
> -           (collect (xdg-desktop-read-file file))))
A few changes from the original one:
- replaced `file-exists-p` with `file-directory-p`, which return t only when it's an existing directory
- duplicated autostart directories are filtered out

2021-06-02 06:18 UTC, JAremko commented
/rebase

2021-06-02 06:52 UTC, moritzschaefer commented
@lebensterben let me know if I should do anything.. :)

2021-06-02 07:01 UTC, lebensterben commented
@moritzschaefer 
Can you see the comments I left?

2021-06-05 09:45 UTC, lebensterben commented
@moritzschaefer 

Can you verify whether it's working?

2021-06-05 12:27 UTC, moritzschaefer commented
Hey @lebensterben. Sorry, I really just wanted to fix these syntax errors and at the moment don't have time for testing and reviewing all the changes. So I'd suggest to just merge it.

2021-06-05 13:59 UTC, lebensterben commented
@moritzschaefer 
Don't worry. I will take my time until it's verified working.

2021-06-05 14:58 UTC, moritzschaefer commented
I quickly pulled the branch and restarted my system. There are neither errors/warnings nor is there any abnormal behavior. Thanks for the effort!

2021-06-05 15:02 UTC, merged

2021-06-05 15:03 UTC, lebensterben commented
@moritzschaefer 
merged. thanks for your contributiuon