Fix guide on logo for the Ubuntu users
syl20bnr/spacemacs pull request #14871
Opened 2021-06-24 06:08 UTC by popzxc

Fixes #14860 

Replaced the dead link with the instructions mentioned in the issue.

2021-06-24 06:21 UTC, lebensterben commented
We should instruct users to use https://github.com/emacs-mirror/emacs/blob/3af9e84ff59811734dcbb5d55e04e1fdb7051e77/etc/emacs.desktop as reference.

2021-06-24 15:31 UTC, lebensterben requested changes

2021-06-24 15:31 UTC, lebensterben commented on README.md
> +[Desktop Entry]
What I meant was we don't need to have this code section.

Just link to Emacs original desktop file and tell user which field to add/modify.

2021-06-24 20:09 UTC, lebensterben requested changes

2021-06-24 20:09 UTC, lebensterben commented on README.md
> +You can find the default `.desktop` file example in the [emacs repository][desktop_file_example].
We'd better tell people to put the desktop file in `~/.local/share/applications`

2021-06-24 20:09 UTC, lebensterben commented on README.md
>  [desktop_file_example]: https://github.com/emacs-mirror/emacs/blob/3af9e84ff59811734dcbb5d55e04e1fdb7051e77/etc/emacs.desktop
replace the link with
https://github.com/emacs-mirror/emacs/blob/master/etc/emacs.desktop

2021-06-24 20:09 UTC, lebensterben commented on README.md
> +In this file, you must change `Icon` section to `Icon=/PATH/TO/.emacs.d/core/banners/img/spacemacs.png`,
`Icon` is not a section.
A section is what bettwen `[` and `]`.

---

Also note that user can optionally change the `Name` field to `Spacemacs` to distinguish it from the desktop entry of vanilla Emacs.

2021-06-25 04:07 UTC, popzxc commented
Fixed. If you have more comments, please add them as code suggestions wherever possible.

2021-06-25 06:25 UTC, lebensterben requested changes

2021-06-25 06:25 UTC, lebensterben commented on README.md
> +Kudos to [@cpaulik](https://github.com/cpaulik) for writing the original guide.
Nothing to kudo since we're not using his desktop file.

2021-06-25 06:25 UTC, lebensterben commented on README.md
> +### Ubuntu users
This section needs to be improved.
You can well describe it in a coherent paragraph.
What I see now are a bunch of broken sentences.
Whenever writing anything, you'd better read it.

2021-06-25 06:32 UTC, popzxc commented
Sorry, but it starts to feel that I have to rewrite this section over and over, while initially, I was only aiming to do what was proposed in the original issue:

> You can create a PR to fill in this information into the README file, just make sure to properly credit the original author of the page.

I guess I don't have enough motivation to keep working on this 🤷

2021-06-25 06:32 UTC, closed without merging