Add twitch layer
syl20bnr/spacemacs pull request #14980
Opened 2021-08-09 15:03 UTC by BenediktBroich

This layer adds support for twitch. You can search for streamers and open the stream in the browser.
If the =erc= layer is enabled you are able to connect to twitch irc and join the streamer channel.
If the =streamlink= layer is enabled the streams are opened with streamlink. (Pull request is open)

2021-08-09 15:04 UTC, BenediktBroich commented
streamlink layer: https://github.com/syl20bnr/spacemacs/pull/14979

2021-08-16 20:37 UTC, lebensterben approved these changes
LGTM

2021-08-16 20:40 UTC, lebensterben commented on layers/+web-services/twitch/packages.el
> +                 ;; :toggle (configuration-layer/package-usedp 'helm)
One issue is this depends on `helm` so you indeed need some "toggle".
Here you can use `:requires`.

2021-08-23 22:15 UTC, lebensterben commented on layers/+web-services/twitch/packages.el
> +    ;; (erc-twitch :toggle (configuration-layer/package-usedp 'erc))
```suggestion
    ;; (erc-twitch :toggle (configuration-layer/package-usedp 'erc))
```

2021-08-23 22:20 UTC, lebensterben requested changes
There's no significant issue with this PR. But there's also no significant feature either.

I'd prefer to see a new layer to include more features/configurations rather than just being a collection of packages.

2021-09-11 21:20 UTC, smile13241324 commented
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.

2021-09-11 21:20 UTC, closed without merging