latex layer add auto configure pdf-tools and open in split window
syl20bnr/spacemacs pull request #15028
Opened 2021-08-31 21:10 UTC by dalanicolai

Due to some question on Gitter, and some struggle to find the correct answer,
 I propose to add the following sane configuration options to the latex layer
(It is anyway nice to be able to allow for configuring these things with layer variables).

I did not write the documentation because I first "poll" for your opinion. So let me
 know if you think that I should finish this PR.
 
This commit makes the latex layer automatically configure pdf-tools as
latex pdf-viewer if the pdf layer is installed (or use another viewer by setting the
`latex-view-with-pdf-tools` variable to nil).

Additionally, it adds a layer variable for configuring Spacemacs to open pdf-view in a
split-window. (Strangely, finding out how to achieve that is far from trivial,
and also not easy to google, because many hits do not provide the "correct"
answer (see the typical example
[here](https://emacs.stackexchange.com/questions/28056/spacemacs-latex-how-to-make-view-command-tile-vertically-with-emacs-window)).

2021-09-01 20:55 UTC, lebensterben commented on layers/+lang/latex/funcs.el
> +  (when latex-view-with-pdf-tools
what if a user set it to `t` while `pdf-tools` is not used?

```elisp
(when latex-view-with-pdf-tools
  (if (configuration-layer/layer-used-p 'pdf)
      ;; THEN
    ;; show a warning
```

2021-09-01 20:57 UTC, lebensterben requested changes
LGTM.
Just one minor issue.

Also needs to update CHANGELOG.develop and README.org

2021-09-02 21:13 UTC, lebensterben commented on layers/+lang/latex/funcs.el
> +  "Conditionally setup pdf-tools"
```suggestion
  "Conditionally setup pdf-tools."
```

2021-09-04 19:38 UTC, smile13241324 commented
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop.

2021-09-04 19:38 UTC, closed without merging