Add Svelte layer
syl20bnr/spacemacs pull request #15084
Opened 2021-10-04 08:40 UTC by msuess

This PR adds support for Svelte based on the excellent Vue layer by Thanh Vuong.

2021-10-20 11:01 UTC, msuess commented
Thanks for the review! I'm assuming you mean the double newlines after the first comment? I can remove them if this is blocking the merge, but I just copied most of the code over from the vue layer, where they are also present.

2021-11-06 13:54 UTC, smile13241324 requested changes
I have reviewed your commit and found some points you need to double check before this can be merged.

2021-11-06 13:54 UTC, smile13241324 commented on layers/+frameworks/svelte/config.el
> +;;; config.el --- vue layer config file for Spacemacs. -*- lexical-binding: t -*-
This should be svelte layer not vue
```suggestion
;;; config.el --- svelte layer config file for Spacemacs. -*- lexical-binding: t -*-
```

2021-11-06 13:54 UTC, smile13241324 commented on layers/+frameworks/svelte/config.el
> +;; Author: Thanh Vuong <thanhvg@gmail.com>
You should be the author :)

2021-11-06 13:54 UTC, smile13241324 commented on layers/+frameworks/svelte/funcs.el
> +;; Author: Thanh Vuong <thanhvg@gmail.com>
You should be the author ;)

2021-11-06 13:54 UTC, smile13241324 commented on layers/+frameworks/svelte/funcs.el
> +                                  :variables company-minimum-prefix-length 2)
This should rather be set in the users dotfile

2021-11-06 13:54 UTC, smile13241324 commented on layers/+frameworks/svelte/layers.el
> +;;; layers.el --- react Layer layers File for Spacemacs
Should be svelte layer

2021-11-06 13:54 UTC, smile13241324 commented on layers/+frameworks/svelte/layers.el
> +;; Author: Thanh Vuong <thanhvg@gmail.com>
You should be the author

2021-11-06 13:54 UTC, smile13241324 commented on layers/+frameworks/svelte/layers.el
> +(configuration-layer/declare-layers '(node html prettier javascript))
You should declare a dependency on lsp layer when the backend lsp is used

2021-11-13 09:24 UTC, smile13241324 commented
Thank you for contributing to spacemacs 💜, I have cherry picked your commit into develop as I was doing some refactoring anyway I have fixed the open points on the go.

2021-11-13 09:24 UTC, closed without merging

2021-12-02 11:17 UTC, msuess commented
Thank you!