Add systemctl layer
syl20bnr/spacemacs pull request #15288
Opened 2022-01-26 17:00 UTC by BenediktBroich

This layer adds support for viewing log files with =journalctl= in Spacemacs. This is a major-mode for emacs to view systemd's journalctl output in emacs. The output is split into chunks for performance reasons. Fontification is provided and may be customized.

2022-01-27 10:25 UTC, tko commented
Seems like this would fit in the existing `systemd` layer?

2022-01-27 13:22 UTC, BenediktBroich commented
I can change that. Are the Keybinding ok?

2022-01-29 20:59 UTC, lebensterben requested changes

2022-01-29 20:59 UTC, lebensterben commented on layers/+tools/systemd/README.org
> +* Journalctl-mode
These should be added under the `features` section above.

2022-01-29 20:59 UTC, lebensterben commented on layers/+tools/systemd/README.org
> +** Key Bindings
the key bindings for journalctl-mode should be added under the `* Key bindings` section

2022-01-29 20:59 UTC, lebensterben commented on layers/+tools/systemd/packages.el
> +              ))))
closing parentheses should not take a new line.

2022-01-31 17:49 UTC, lebensterben commented on layers/+tools/systemd/README.org
> +- Viewing systemd unit via [[https://github.com/SebastianMeisel/journalctl-mode][journalctl-mode]]
Can you combine this two lines?

> Viewing systemd system and user unit via [[https://github.com/SebastianMeisel/journalctl-mode][journalctl-mode]]

2022-01-31 21:41 UTC, lebensterben approved these changes
LGTM

2022-01-31 21:48 UTC, merged

2022-01-31 21:49 UTC, lebensterben commented
Merged. Thanks for your contributions.

2022-02-25 14:44 UTC, arifer612 commented on layers/+tools/systemd/packages.el
> +    :ensure t
What's the purpose of having `:ensure t` instead of deferring it like all the other packages?