[editing-visual] add mixed-pitch
syl20bnr/spacemacs pull request #15319
Opened 2022-02-06 03:25 UTC by thanhvg

Add this https://gitlab.com/jabranham/mixed-pitch

2022-02-06 04:08 UTC, lebensterben requested changes
LGTM. All requests are about documentation.

2022-02-06 04:08 UTC, lebensterben commented on layers/+emacs/org/README.org
> +Set the variable =org-enable-mixed-pitch= to =t=.
Please also add a warning/note about the interaction with company.
See `Interaction with company` section on its repository.

2022-02-06 04:08 UTC, lebensterben commented on layers/+lang/asciidoc/README.org
> +** Mixed pitched support
Please also add a warning/note about the interaction with company.
See `Interaction with company` section on its repository.

2022-02-06 04:08 UTC, lebensterben commented on layers/+lang/markdown/README.org
> +** Mixed pitched support
Please also add a warning/note about the interaction with company.
See `Interaction with company` section on its repository.

2022-02-06 04:08 UTC, lebensterben commented on layers/+spacemacs/spacemacs-editing-visual/README.org
> +* Mixed pitch fonts support
Please also add a warning/note about the interaction with company.
See `Interaction with company` section on its repository.

2022-02-07 03:39 UTC, lebensterben requested changes
@thanhvg 

After more considerations, I think it's better to do the following instead:

- Make a new layer in `fonts` category with this single package.
- Make a layer variable for example `mixed-pitch-enabled-modes` and defaults to `'(org markdown asciidoc)`
- In the `packages.org` of the layer, for each mode in `mixed-pitch-enabled-modes`, add a hook.
- Also don't forget to update the CHANGELOG

2022-02-13 20:28 UTC, lebensterben commented
@thanhvg 
Please review the changes I made.

This should retained the same functionality but I moved the addition to `spacemacs-editing-visual` to a new layer `mixed-pitch`.

And there's no changes to `markdown` or `asciidoc` layers.

I will add you to co-author once I squash the commits and merge them.

2022-02-14 02:54 UTC, thanhvg commented
Sorry I'm not having much free time for the last few weeks. I am not a big fan of one package layer. It's convoluted going though all the layer boilerplate to have it in while it can be enabled and support everything inside `dotspacemacs/user-config`. For mixed pitch I think it fits my individual taste more than the community's so I 'd rather close this PR.

One more thing you guys should deprecate CHANGELOG too and enforce better git commit messages instead.

2022-02-14 02:54 UTC, closed without merging

2022-02-14 03:03 UTC, lebensterben commented
@thanhvg 
I also don't like one package layer. But we don't currently have any layer configuration variable for any `spacemacs-*` layers.

Because by default these `spacemacs-*` layers are implicitly enabled when you choose the `spacemacs` distribution. Unless the user chose `spacemacs-base` distribution, he won't be able to specify a layer config variable.