Added documentation to set julia envornment location for lsp server
syl20bnr/spacemacs pull request #15675
Opened 2022-08-03 21:07 UTC by dCaples

lsp-julia-default-envornment is set by default to ~/.julia/environments/v1.0 .
To make the lsp server show completions for installed packages, the environment
location must be the same as that of the installed julia version enviornment.
Documentation was added to notify users to set the emacs variable to their
enviornment location.

Thank you :heart: for contributing to Spacemacs!

Before you submit this pull request, please ensure it is against the `develop` branch and that you have read the [CONTRIBUTING.org](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org) file. It contains instructions on how to properly follow our conventions on commit messages, documentation, change log entries and other elements.

Don't forget to update CHANGELOG.develop if you want to be mentioned in the release file!

This message should be replaced with a description of your change.

Cheers!

2022-08-03 22:26 UTC, lebensterben commented
I suggest to add a reference link to Julia's language server on the environment variable.

2022-08-04 05:49 UTC, smile13241324 requested changes
Looks ok still a link to the respective emacs-lsp config page and the projects page of the lsp should be added, to notify users about other config vars for this particular language server.

2022-08-05 02:05 UTC, dCaples commented
ok, I implemented your suggestion! I didn't include the [emacs-lsp config page](https://emacs-lsp.github.io/lsp-mode/page/lsp-julia/) because it didn't really contain any information, and the links in it were already included in the docs. I can include it if you still think it would still be useful.

2022-08-05 03:13 UTC, lebensterben approved these changes

2022-08-05 21:30 UTC, merged