[search-engine] add google-this package
syl20bnr/spacemacs pull request #15912
Opened 2023-02-09 19:24 UTC by bb2020

2023-02-09 19:28 UTC, lebensterben requested changes

2023-02-09 19:28 UTC, lebensterben commented on layers/+web-services/search-engine/packages.el
> +      (with-eval-after-load 'google-this
if you use this it means you should use :config

2023-02-09 19:28 UTC, lebensterben commented on layers/+web-services/search-engine/packages.el
> +        (fset 'google-this-url (lambda () "https://www.google.com/search?q=%s&pws=0&gl=us&gws_rd=cr"))))))
this is bad for two reasons:

1. you assumed language and region
2. you can define a function normally instead of using fset

2023-02-09 19:39 UTC, lebensterben commented
You can add them in a private layer or add them in user-config.

2023-02-09 19:39 UTC, closed without merging

2023-02-09 19:55 UTC, bb2020 commented
Why are you instantly closing pull requests? I would have fixed it with your suggestions.

2023-02-09 20:01 UTC, lebensterben commented
see the comment https://github.com/syl20bnr/spacemacs/pull/15912#issuecomment-1424715089

2023-02-09 20:05 UTC, bb2020 commented
Of course I know there is user config. This is not a proper way to maintain an open source project. If you don't want contributions, you should archive this repository.

2023-02-09 20:08 UTC, lebensterben commented
also, this is far superior https://github.com/hrs/engine-mode/tree/a5f1ae2b087109f37a704c496942cec9d9f48698

2023-02-09 20:10 UTC, lebensterben commented
> If you don't want contributions

that's not true.

I closed this issue because 

1. engine-mode is far better than your new addition.
2. the code quality is awful.
3. we had internal discussion before to discourage PR that introduces trivial functionality like this.

2023-02-10 19:09 UTC, bb2020 commented
Can I add the URL into `search-engine-alist` with this PR?
Because regional Google sites are pretty bad for tech related searches.

2023-02-10 19:31 UTC, lebensterben commented
There is already a Google entry. Your addition in the PR and you later suggestion is simply meaningless.

2023-02-10 19:35 UTC, bb2020 commented
The Google entry yields bad results when you are abroad, because it uses regional websites. I wanted to add a Google US entry that would be helpful for many people.

2023-02-10 20:32 UTC, lebensterben commented
> The Google entry yields bad results when you are abroad, because it uses regional websites. 

It uses regional website so what?
The search region doesn't depend on which Goolge you're accessing.

Then if you've logged in your Google account, it will use your normal region and language settings.

Meanwhile your PR hardcoded geo location which is indeed erroneous for most people on this world.

2023-02-10 20:44 UTC, bb2020 commented
If you can reopen the PR, you will see what I meant.

2023-02-10 20:48 UTC, lebensterben commented
are we going to add entries for each region?

2023-02-10 20:49 UTC, bb2020 commented
It literally says regionless.