Enable auto-yasnippet for company
syl20bnr/spacemacs pull request #16260
Opened 2024-01-24 12:45 UTC by gbastkowski

In https://github.com/syl20bnr/spacemacs/pull/16176 the auto-yasnippet package has been toggled off for company auto-completion. I am not sure if that was really intended. I would like to have it available.

2024-01-24 17:16 UTC, bcc32 commented
This PR changes auto-yasnippet to be toggled on _only for company_ and not if company is disabled.  Is that intentional?

2024-01-25 07:41 UTC, gbastkowski commented
No, it was not.

2024-02-01 15:51 UTC, smile13241324 requested changes
I have found a small issue please have a look and ping me when you are ready for another review.

2024-02-01 15:51 UTC, smile13241324 commented on layers/+completion/auto-completion/packages.el
> +      "iSh" 'spacemacs/auto-yasnippet-expand-from-history
I think you should add your new binding into the layer readme.

2024-02-17 14:06 UTC, smile13241324 approved these changes

2024-02-17 14:06 UTC, merged