Fix create-layer function for compleseus
syl20bnr/spacemacs pull request #16342
Opened 2024-03-30 17:28 UTC by fnussbaum

Fixes #15913

2024-03-30 20:25 UTC, bcc32 commented
FWIW, `ivy-read` with these arguments is equivalent to just `completing-read`, so I think the only special case needed is helm, here.

2024-03-31 10:08 UTC, fnussbaum commented
Good point, thanks!

2024-04-03 19:30 UTC, smile13241324 requested changes
Please have a look at my review comment

2024-04-03 19:30 UTC, smile13241324 commented on core/core-configuration-layer.el
> +                                                    (list other-choice)))))
Are you sure we do not need ivy read here too?

2024-04-03 19:37 UTC, smile13241324 approved these changes

2024-04-03 19:37 UTC, smile13241324 commented
Ups missed the last comment

2024-04-03 19:38 UTC, merged