[go] Disable use of company-go when gopls is used
syl20bnr/spacemacs pull request #16392
Opened 2024-05-09 10:27 UTC by rawenous

The default backend for go-layer is lsp but company-go was still added to company-backends forcing it to search for gocode which should not be used since the user wants lsp.

This change only adds company-go to company-backends if go-mode is selected as the backend.

Note: go-mode is deprecated and gocode is not maintained anymore

2024-05-09 10:29 UTC, rawenous commented
This may not be the optimal way of solving this so please let me know if there is a more correct emacs/spacemacs way.

This seems to solve #11217 and adds the last cleanup needed for #13863

2024-05-13 19:57 UTC, smile13241324 requested changes
I think you should rather put a condition on the company go package itself so that it is not installed at all, right now we are installing it but never use it.

A good example for this is the package flycheck-golangci-lint.

2024-05-13 21:10 UTC, rawenous commented
Thanks. I will take a look at it.

2024-05-15 15:22 UTC, smile13241324 requested changes

2024-05-15 15:22 UTC, smile13241324 commented on layers/+lang/go/packages.el
> +    (company-go :requires company
I think you need to also cover the case when there is no go backend.

2024-05-15 20:08 UTC, rawenous commented on layers/+lang/go/packages.el
> +    (company-go :requires company
@smile13241324, I don't fully understand. Today go-backend is either set to _lsp_ or _go-mode_ so there is always a go-backend selected. I can add _nil_ as an option that will load neither lsp or company-go.

2024-05-20 05:46 UTC, smile13241324 commented on layers/+lang/go/packages.el
> +    (company-go :requires company
Sorry my mistake some layers don't set this var reliably and have some code for inferring if lsp is selected from the layer configuration if this is not the case here its ok.

2024-05-20 05:46 UTC, smile13241324 approved these changes

2024-05-20 05:46 UTC, merged