Fix validation of `dotspacemacs-swap-number-row`
syl20bnr/spacemacs pull request #16419
Opened 2024-05-28 15:07 UTC by fnussbaum

Fixes #16417

2024-05-30 14:04 UTC, smile13241324 requested changes
I think the comments in the dot file template also need to be changed.

2024-05-30 22:15 UTC, fnussbaum commented
The comment in the template seems to be up to date in the sense that it includes `querty-ca-fr` already:
```elisp
  ;; If non-nil shift your number row to match the entered keyboard layout
   ;; (only in insert state). Currently supported keyboard layouts are:
   ;; `qwerty-us', `qwertz-de' and `querty-ca-fr'.
   ;; New layouts can be added in `spacemacs-editing' layer.
   ;; (default nil)
   dotspacemacs-swap-number-row nil
```
@smile13241324 Is there something else that needs to be changed?

2024-05-31 04:05 UTC, smile13241324 commented
Nope that's fine then

2024-05-31 04:06 UTC, smile13241324 approved these changes

2024-05-31 04:06 UTC, merged